# AkiAsync Configuration File
# Async optimization plugin for Leaves server

# Entity Tracker Async Optimization
entity-tracker:
  # Enable async entity tracker
  enabled: true
  # Number of threads in the async executor pool
  # Recommended: CPU cores (for most servers 4-8 is good)
  # Min: 1, Max: 32
  thread-pool-size: 4
  # Update interval in ticks (20 ticks = 1 second)
  # Lower values = more frequent updates but higher CPU usage
  # Default: 1 (every tick)
  update-interval-ticks: 1
  # Maximum queue size for async tasks
  # If queue is full, tasks will be executed synchronously as fallback
  max-queue-size: 1000
  # Async mod: Batch processing size (default: 50)
  # Accumulate N tracking tasks before submitting to thread pool
  # Higher = better throughput but slightly higher latency
  # Lower = lower latency but more thread overhead
  # Recommended: 30-100
  batch-size: 50

# Mob Spawning Async Optimization
mob-spawning:
  # Enable async mob spawning optimization
  enabled: true
  # Enable spawner block optimization
  # Optimizes mob spawner performance
  spawner-optimization: true

# Density & Pathfinding Controls
density:
  # Max entities per chunk (all mobs) before farm-mode mitigation kicks in
  max-per-chunk: 80

pathfinding:
  # Total pathfinding budget per tick (estimated tasks). 0 disables limit
  tick-budget: 0

# Brain throttle & Expensive AI async processing
brain:
  # Enable throttling for stationary mobs AI brain.tick
  throttle: true
  # Only think once per N ticks when stationary
  throttle-interval: 10

# Async AI - Zero Latency Brain Execution (零延迟异步AI)
# 核心思路：主线程只读POI快照，Brain异步执行，同tick内写回
# 针对不同生物类型提供独立的优化开关
async-ai:
  # Global timeout in microseconds (100μs = 0.1ms)
  # 全局超时时间（微秒）- 中期优化：砍半超时，让线程池真正忙起来
  timeout-microseconds: 100
  
  # Execution mode (执行模式)
  # simple: 简单CPU计算模拟（方案1：30秒止血）
  # full: 完整异步Brain执行（方案2：10分钟真异步）
  mode: simple
  
  # 村民类优化 (Villager + Wandering Trader)
  # 村民依赖POI系统（床、工作站等），需要POI快照
  villager-optimization:
    enabled: false  # 默认关闭（实验性）
    use-poi-snapshot: true  # 使用POI快照（村民必须）
  
  # 猪灵+猪灵蛮兵优化 (Piglin + PiglinBrute)
  # 猪灵/蛮兵：金币检测+以物易物+恐惧向量，CPU密集
  # 50只猪灵 = 40-50 ms MSPT → 直接吃掉2个TPS
  # 包含实体：minecraft:piglin, minecraft:piglin_brute
  piglin-optimization:
    enabled: false  # 默认关闭，需手动启用
    use-poi-snapshot: false  # 猪灵不依赖POI，使用自定义快照
    look-distance: 16  # 注视距离（格）
    barter-distance: 16  # 交易距离（格，蛮兵也检测）
  
  # 女巫优化 (Witch)
  # 女巫：药水配方+效果检测+攻击目标筛选，CPU密集
  # 30只女巫 = 27-33 ms MSPT → 直接吃掉1.5个TPS
  witch-optimization:
    enabled: false  # 默认关闭
    use-poi-snapshot: false  # 女巫不依赖POI
    scan-distance: 16  # 扫描距离（格）
  
  # 其他生物优化 (简单AI实体)
  # 僵尸、骷髅、苦力怕等不依赖POI的生物
  simple-entities:
    enabled: false
    use-poi-snapshot: false  # 简单实体无需POI快照

# Parallel EntityTickList (biggest hotspot ~75%)
# 扩容优化：实体级分批（chunk粒度太粗 → 8-entity小批次）
entity-tick-parallel:
  # Enable parallel entity ticking
  enabled: true
  # Number of parallel threads (recommend: 4-8)
  threads: 6
  # Minimum entities to trigger parallel (avoid overhead for small lists)
  min-entities: 50
  # Batch size (entities per task, 实体级粒度)
  # 8 = 均衡任务大小，避免chunk粒度太粗（0~150+实体差异巨大）
  batch-size: 8

# ServerCore-inspired optimizations
servercore-optimizations:
  # Optimize pushEntities (26.72% hotspot)
  push-optimization:
    enabled: true
    # Only push every N ticks (2 = every other tick)
    interval: 2
  
  # Cache entity lookup results (23.12% hotspot)
  entity-lookup-cache:
    enabled: true
    # Cache validity duration in milliseconds
    duration-ms: 50
  
  # Optimize collision detection (9% hotspot)
  collision-optimization:
    enabled: true
    # Minimum movement to trigger collision checks (squared)
    min-movement: 0.001

# FerriteCore-inspired memory optimizations
memory-optimizations:
  # Cache common predicates to reduce GC pressure
  predicate-cache:
    enabled: true
  
  # BlockPos object pool to reduce allocations (~26% reduction)
  blockpos-pool:
    enabled: true
  
  # Pre-allocate entity lists to reduce ArrayList resizing
  list-prealloc:
    enabled: true
    # Default initial capacity for entity lists
    default-capacity: 32

# FabricFastFurnace-inspired block entity optimization
block-entity-optimizations:
  # Skip furnace ticks when idle (no fuel/items)
  furnace-optimization:
    enabled: true

# ScalableLux/Starlight-inspired lighting optimizations
lighting-optimizations:
  # Async lighting calculation (reduces main thread load during chunk loading)
  async-lighting:
    enabled: true
    # Dedicated thread pool size for lighting (recommend: 2-4)
    thread-pool-size: 2
    # Batch threshold - accumulate N updates before processing
    # Higher = better throughput, lower = lower latency
    # This is the base threshold, actual value adjusts dynamically based on TPS
    batch-threshold: 16
  
  # Light propagation queue optimization (Starlight algorithm)
  propagation-queue:
    # Use true layered propagation queue (16 levels, 0-15 light levels)
    # Starlight core algorithm - processes from high to low light levels
    use-layered-queue: true
    # Maximum light propagation distance per batch
    # Lower values reduce lag spikes from large light updates
    max-propagation-distance: 15
  
  # Skylight cache (reduces repeated calculations)
  skylight-cache:
    enabled: true
    # Cache validity duration in milliseconds
    cache-duration-ms: 100
  
  # Advanced optimizations
  advanced:
    # Enable deduplication (prevents same position from queuing multiple times)
    enable-deduplication: true
    # Enable dynamic batch size adjustment based on server TPS
    # When TPS < 18: batch size increases (reduce overhead)
    # When TPS > 19.8: batch size decreases (lower latency)
    dynamic-batch-adjustment: true
    # Log advanced optimization statistics
    log-advanced-stats: false

# Performance Settings
performance:
  # Enable debug logging (useful for troubleshooting)
  # Warning: This can spam your console!
  debug-logging: false
  
  # Enable performance metrics collection
  # Shows async task execution times and queue sizes
  enable-metrics: true

# ========================================
# Configuration Tips:
# ========================================
# 1. For small servers (1-10 players): thread-pool-size: 2-4
# 2. For medium servers (10-50 players): thread-pool-size: 4-8
# 3. For large servers (50+ players): thread-pool-size: 8-16
# 
# Note: More threads doesn't always mean better performance!
# Start with 4 threads and adjust based on your server's needs.

